### ISSUE TITLE
bug -- invalid scheme test

### ISSUE THREAD

**Issue by pvinuesa** [Victorian-Bioinformatics-Consortium/mlst#4]
Hi Torsten, thanks for posting the mlst code. I just cloned it and gave it a try. Had to do the minor change to line 58  shown below, to make the test for valid $scheme work and the script to run. The string equality test always returns FALSE, as $_ contains the full-path preceding the dir names!

#die "Invalid scheme: $scheme" unless ( grep { $_ eq $scheme } @sc ); 
die "Invalid scheme: $scheme" unless ( grep { $_ =~ /$scheme/ } @sc );

Cheers, 
Pablo

**Comment by tseemann** [comment]
Sorry I missed this before Xmas break.  I think this commit fixes it: 781c80e9ace9ad8ab4503ddcfe7c22d9855506d7
